
# Inprogress xlog must be renamed before second insert.

space = box.schema.create_space('tweedledum', { id = 0 })
---
...
00000000000000000002.xlog.inprogress exists
space:create_index('primary', 'hash', { parts = { 0, 'num' }})
---
...
00000000000000000002.xlog.inprogress has been successfully renamed

# Inprogress xlog must be renamed during regular termination.

box.space[0]:insert(3, 'third tuple')
---
- [3, 'third tuple']
...
00000000000000000004.xlog.inprogress exists
Stopping the server...
00000000000000000004.xlog.inprogress has been successfully renamed

# An inprogress xlog file with one record must be renamed during recovery.

00000000000000000005.xlog.inprogress hash been successfully renamed

# Empty (zero size) inprogress xlog must be deleted during recovery.

00000000000000000006.xlog.inprogress has been successfully deleted

# Empty (header only, no records) inprogress xlog must be deleted
# during recovery.

00000000000000000006.xlog.inprogress has been successfully deleted

# Inprogress xlog with bad record must be deleted during recovery.

00000000000000000006.xlog.inprogress has been successfully deleted

A test case for https://bugs.launchpad.net/tarantool/+bug/1052018
panic_on_wal_error doens't work for duplicate key errors

box.space[0]:select(0, 1)
---
- [1, 2]
...
box.space[0]:select(0, 2)
---
...
#box.space[0]
---
- 0
...
